world:
  name: house_world
  world_path: "/home/rov-robot/project_ws/src/multi_robot/multi_robot_gazebo/worlds/house.world"
  map_path: "/home/rov-robot/project_ws/src/multi_robot/multi_robot_navigation/maps/map_house.yaml"
robots:
  - name: rover1
    x_pose: 6.0
    y_pose: -1.0
    z_pose: 0.01
    yaw: 1.5708
    rviz_view: "false"
    urdf_path: "/home/rov-robot/colcon_ws/src/car_gps/rtk_gps_description/urdf/adl200_description.urdf.xacro"
    sdf_path: ""
    nav_param_path: "/home/rov-robot/colcon_ws/src/car_gps/rtk_gps_navigation/param/rtk.yaml"
  - name: limo1
    x_pose: -1.5
    y_pose: 0.5
    z_pose: 0.01
    yaw: 0.0
    rviz_view: "false"
    urdf_path: "/home/rov-robot/colcon_ws/src/limo_ros2/limo_description/urdf/limo_four_diff.xacro"
    sdf_path: ""
    nav_param_path: "/home/rov-robot/colcon_ws/src/limo_ros2/limo_bringup/param/navigation2.yaml"
  - name: tb3
    x_pose: -6.5
    y_pose: -2.0
    z_pose: 0.01
    yaw: 1.5708
    rviz_view: "false"
    urdf_path: "/home/rov-robot/colcon_ws/src/turtlebot3_simulations/turtlebot3_gazebo/urdf/turtlebot3_waffle_pi.urdf"
    sdf_path: "/home/rov-robot/colcon_ws/src/turtlebot3_simulations/turtlebot3_gazebo/models/turtlebot3_waffle_pi/model.sdf"
    nav_param_path: "/home/rov-robot/colcon_ws/src/turtlebot3/turtlebot3_navigation2/param/waffle_pi.yaml"