world:
  name: warehouse_world
  world_path: "/home/rov-robot/colcon_ws/src/aws-robomaker-small-warehouse-world/worlds/no_roof_small_warehouse/no_roof_small_warehouse.world"
  map_path: "/home/rov-robot/colcon_ws/src/aws-robomaker-small-warehouse-world/maps/005/map.yaml"
robots:
  - name: tb1_1
    x_pose: 0.2
    y_pose: 0.3
    z_pose: 0.01
    yaw: 0.0
    rviz_view: "false"
    urdf_path: "/home/rov-robot/colcon_ws/src/turtlebot3_simulations/turtlebot3_gazebo/urdf/turtlebot3_waffle.urdf"
    sdf_path: "/home/rov-robot/colcon_ws/src/turtlebot3_simulations/turtlebot3_gazebo/models/turtlebot3_waffle/model.sdf"
    nav_param_path: "/home/rov-robot/colcon_ws/src/turtlebot3/turtlebot3_navigation2/param/waffle.yaml"
  - name: tb2_1
    x_pose: 0.2
    y_pose: -0.1
    z_pose: 0.01
    yaw: 0.0
    rviz_view: "false"
    urdf_path: "/home/rov-robot/colcon_ws/src/turtlebot3_simulations/turtlebot3_gazebo/urdf/turtlebot3_waffle.urdf"
    sdf_path: "/home/rov-robot/colcon_ws/src/turtlebot3_simulations/turtlebot3_gazebo/models/turtlebot3_waffle/model.sdf"
    nav_param_path: "/home/rov-robot/colcon_ws/src/turtlebot3/turtlebot3_navigation2/param/waffle.yaml"
  - name: tb3_1
    x_pose: 0.2
    y_pose: -0.5
    z_pose: 0.01
    yaw: 0.0
    rviz_view: "false"
    urdf_path: "/home/rov-robot/colcon_ws/src/turtlebot3_simulations/turtlebot3_gazebo/urdf/turtlebot3_waffle.urdf"
    sdf_path: "/home/rov-robot/colcon_ws/src/turtlebot3_simulations/turtlebot3_gazebo/models/turtlebot3_waffle/model.sdf"
    nav_param_path: "/home/rov-robot/colcon_ws/src/turtlebot3/turtlebot3_navigation2/param/waffle.yaml"
  - name: tb4_2
    x_pose: -2.3
    y_pose: 0.3
    z_pose: 0.01
    yaw: 3.1416
    rviz_view: "false"
    urdf_path: "/home/rov-robot/colcon_ws/src/turtlebot3_simulations/turtlebot3_gazebo/urdf/turtlebot3_waffle_pi.urdf"
    sdf_path: "/home/rov-robot/colcon_ws/src/turtlebot3_simulations/turtlebot3_gazebo/models/turtlebot3_waffle_pi/model.sdf"
    nav_param_path: "/home/rov-robot/colcon_ws/src/turtlebot3/turtlebot3_navigation2/param/waffle_pi.yaml"
  - name: tb5_2
    x_pose: -2.3
    y_pose: -0.1
    z_pose: 0.01
    yaw: 3.1416
    rviz_view: "false"
    urdf_path: "/home/rov-robot/colcon_ws/src/turtlebot3_simulations/turtlebot3_gazebo/urdf/turtlebot3_waffle_pi.urdf"
    sdf_path: "/home/rov-robot/colcon_ws/src/turtlebot3_simulations/turtlebot3_gazebo/models/turtlebot3_waffle_pi/model.sdf"
    nav_param_path: "/home/rov-robot/colcon_ws/src/turtlebot3/turtlebot3_navigation2/param/waffle_pi.yaml"
  - name: tb6_2
    x_pose: -2.3
    y_pose: -0.5
    z_pose: 0.01
    yaw: 3.1416
    rviz_view: "false"
    urdf_path: "/home/rov-robot/colcon_ws/src/turtlebot3_simulations/turtlebot3_gazebo/urdf/turtlebot3_waffle_pi.urdf"
    sdf_path: "/home/rov-robot/colcon_ws/src/turtlebot3_simulations/turtlebot3_gazebo/models/turtlebot3_waffle_pi/model.sdf"
    nav_param_path: "/home/rov-robot/colcon_ws/src/turtlebot3/turtlebot3_navigation2/param/waffle_pi.yaml"
