world:
  name: warehouse_world
  world_path: "/home/rov-robot/colcon_ws/src/aws-robomaker-small-warehouse-world/worlds/no_roof_small_warehouse/no_roof_small_warehouse.world"
  map_path: "/home/rov-robot/colcon_ws/src/aws-robomaker-small-warehouse-world/maps/005/map.yaml"
robots:
  - name: diff500
    x_pose: 0.0
    y_pose: 0.25
    z_pose: 0.01
    yaw: 0.0
    rviz_view: "false"
    urdf_path: "/home/rov-robot/colcon_ws/src/neo_simulation2/robots/mp_500/mp_500.urdf"
    sdf_path: ""
    nav_param_path: "/home/rov-robot/colcon_ws/src/neo_simulation2/configs/mp_500/navigation.yaml"
  - name: mpo700_1
    x_pose: -0.1
    y_pose: -0.6
    z_pose: 0.01
    yaw: 0.0
    rviz_view: "false"
    urdf_path: "/home/rov-robot/colcon_ws/src/neo_simulation2/robots/mpo_700/mpo_700.urdf"
    sdf_path: ""
    nav_param_path: "/home/rov-robot/colcon_ws/src/neo_simulation2/configs/mpo_700/navigation.yaml"
  - name: mpo700_2
    x_pose: -0.1
    y_pose: -1.5
    z_pose: 0.01
    yaw: 0.0
    rviz_view: "false"
    urdf_path: "/home/rov-robot/colcon_ws/src/neo_simulation2/robots/mpo_700/mpo_700.urdf"
    sdf_path: ""
    nav_param_path: "/home/rov-robot/colcon_ws/src/neo_simulation2/configs/mpo_700/navigation.yaml"