robots:
  - name: tb1
    is_master: false
    name_master: tb2
    pose_goal_1:
      x: 4.0
      y: 1.0
      z: 0.01
      yaw: 0.0
    pose_goal_2:
      x: -2.0
      y: 4.5
      z: 0.01
      yaw: 1.5708
  - name: tb2
    is_master: true
  - name: tb3
    is_master: false
    name_master: tb5
    pose_goal_1:
      x: -6.5
      y: 2.0
      z: 0.01
      yaw: 0.0
    pose_goal_2:
      x: -4.0
      y: 4.0
      z: 0.01
      yaw: 0.0
    pose_goal_3:
      x: 6.0
      y: -1.0
      z: 0.01
      yaw: 1.5708
  - name: tb4
    is_master: true
  - name: tb5
    is_master: true