robots:
  - name: tb2
    pose_goal_1:
      x: -1.5
      y: 0.5
      z: 0.01
      yaw: 0.0
    pose_goal_2:
      x: -1.4
      y: 0.5
      z: 0.01
      yaw: 0.0
  - name: tb3
    pose_goal_1:
      x: 1.5
      y: 0.5
      z: 0.01
      yaw: 0.0
    pose_goal_2:
      x: 1.4
      y: 0.5
      z: 0.01
      yaw: 0.0
    pose_goal_3:
      x: 1.2
      y: 0.5
      z: 0.01
      yaw: 0.0