robots:
  - name: rover1
    is_master: false
    name_master: limo1
    duration_max_time: 0.15
    pose_goal_1:
      x: -2.0
      y: 4.5
      z: 0.01
      yaw: 1.5708
  - name: limo1
    is_master: true
    same_time_task: false
  - name: tb3
    is_master: false
    name_master: limo1
    duration_max_time: 5.0
    pose_goal_1:
      x: -6.5
      y: 2.0
      z: 0.01
      yaw: 0.0
    pose_goal_2:
      x: -4.0
      y: 4.0
      z: 0.01
      yaw: 0.0
    pose_goal_3:
      x: 6.0
      y: -1.0
      z: 0.01
      yaw: 1.5708