robots:
  - name: tb1
    is_master: false
    name_master: tb2
    duration_max_time: 2.5
    pose_goal_1:
      x: 4.0
      y: 1.0
      z: 0.01
      yaw: 0.0
    pose_goal_2:
      x: -2.0
      y: 4.5
      z: 0.01
      yaw: 1.5708
  - name: tb2
    is_master: true
    same_time_task: false
  - name: tb4
    is_master: false
    name_master: tb5
    duration_max_time: 3.0
    pose_goal_1:
      x: 4.0
      y: 1.0
      z: 0.01
      yaw: 0.0
    pose_goal_2:
      x: -2.0
      y: 3.5
      z: 0.01
      yaw: 1.5708
  - name: tb3
    is_master: false
    name_master: tb5
    duration_max_time: 1.0
    pose_goal_1:
      x: -6.5
      y: 1.5
      z: 0.01
      yaw: 0.0
  - name: tb5
    is_master: true
    same_time_task: true